USE establo;

ALTER TABLE EMPLEADO
    MODIFY nombre        VARCHAR(100)  NOT NULL,
    MODIFY apellido      VARCHAR(100)  NOT NULL,
    MODIFY fecha_contrato DATE          NOT NULL,
    MODIFY salario_base   DECIMAL(10,2) NOT NULL;

ALTER TABLE VACA
    MODIFY arete            VARCHAR(50) NOT NULL,
    MODIFY fecha_nacimiento DATE        NOT NULL,
    MODIFY estado           VARCHAR(50) NOT NULL;

ALTER TABLE CORRAL
    MODIFY capacidad INT NOT NULL;

ALTER TABLE LOTE_PRODUCCION
    MODIFY nombre_lote VARCHAR(100) NOT NULL,
    MODIFY fecha_inicio DATE         NOT NULL;

ALTER TABLE PRODUCCION_LECHE
    MODIFY fecha  DATE         NOT NULL,
    MODIFY litros DECIMAL(5,2) NOT NULL;

ALTER TABLE VENTA_LECHE
    MODIFY fecha           DATE         NOT NULL,
    MODIFY litros_vendidos DECIMAL(8,2) NOT NULL,
    MODIFY precio_por_litro DECIMAL(6,2) NOT NULL;

ALTER TABLE VACA DROP INDEX IF EXISTS uq_vaca_arete;
ALTER TABLE VACA
    ADD CONSTRAINT uq_vaca_arete UNIQUE (arete);

ALTER TABLE ROL DROP INDEX IF EXISTS uq_rol_nombre;
ALTER TABLE ROL
    ADD CONSTRAINT uq_rol_nombre UNIQUE (nombre_rol);

ALTER TABLE LOTE_PRODUCCION DROP INDEX IF EXISTS uq_lote_nombre;
ALTER TABLE LOTE_PRODUCCION
    ADD CONSTRAINT uq_lote_nombre UNIQUE (nombre_lote);

ALTER TABLE EMPLEADO DROP CONSTRAINT IF EXISTS ck_empleado_salario;
ALTER TABLE EMPLEADO
    ADD CONSTRAINT ck_empleado_salario CHECK (salario_base > 0);

ALTER TABLE VACA DROP CONSTRAINT IF EXISTS ck_vaca_estado;
ALTER TABLE VACA
    ADD CONSTRAINT ck_vaca_estado 
        CHECK (estado IN ('ACTIVA','SECA','GESTANTE','TERNERA','VENDIDA','MUERTA'));

ALTER TABLE CORRAL DROP CONSTRAINT IF EXISTS ck_corral_capacidad;
ALTER TABLE CORRAL
    ADD CONSTRAINT ck_corral_capacidad CHECK (capacidad > 0);

ALTER TABLE PRODUCCION_LECHE DROP CONSTRAINT IF EXISTS ck_prod_litros;
ALTER TABLE PRODUCCION_LECHE DROP CONSTRAINT IF EXISTS ck_prod_grasa;
ALTER TABLE PRODUCCION_LECHE DROP CONSTRAINT IF EXISTS ck_prod_solidos;
ALTER TABLE PRODUCCION_LECHE
    ADD CONSTRAINT ck_prod_litros CHECK (litros >= 0),
    ADD CONSTRAINT ck_prod_grasa CHECK (grasa_porcentaje BETWEEN 0 AND 100),
    ADD CONSTRAINT ck_prod_solidos CHECK (solidos_totales_porcentaje BETWEEN 0 AND 100);

ALTER TABLE VENTA_LECHE DROP CONSTRAINT IF EXISTS ck_venta_litros;
ALTER TABLE VENTA_LECHE DROP CONSTRAINT IF EXISTS ck_venta_precio;
ALTER TABLE VENTA_LECHE DROP CONSTRAINT IF EXISTS ck_venta_total;
ALTER TABLE VENTA_LECHE
    ADD CONSTRAINT ck_venta_litros CHECK (litros_vendidos > 0),
    ADD CONSTRAINT ck_venta_precio CHECK (precio_por_litro > 0),
    ADD CONSTRAINT ck_venta_total CHECK (total_venta >= 0);

ALTER TABLE INSUMO DROP CONSTRAINT IF EXISTS ck_insumo_stock;
ALTER TABLE INSUMO DROP CONSTRAINT IF EXISTS ck_insumo_stock_min;
ALTER TABLE INSUMO DROP CONSTRAINT IF EXISTS ck_insumo_precio;
ALTER TABLE INSUMO
    ADD CONSTRAINT ck_insumo_stock CHECK (stock_actual >= 0),
    ADD CONSTRAINT ck_insumo_stock_min CHECK (stock_minimo >= 0),
    ADD CONSTRAINT ck_insumo_precio CHECK (precio_unitario >= 0);

ALTER TABLE COMPRA_INSUMO DROP CONSTRAINT IF EXISTS ck_compra_cantidad;
ALTER TABLE COMPRA_INSUMO DROP CONSTRAINT IF EXISTS ck_compra_costo;
ALTER TABLE COMPRA_INSUMO
    ADD CONSTRAINT ck_compra_cantidad CHECK (cantidad > 0),
    ADD CONSTRAINT ck_compra_costo CHECK (costo_total >= 0);

ALTER TABLE PAGO_EMPLEADO DROP CONSTRAINT IF EXISTS ck_pago_monto;
ALTER TABLE PAGO_EMPLEADO DROP CONSTRAINT IF EXISTS ck_pago_dias;
ALTER TABLE PAGO_EMPLEADO DROP CONSTRAINT IF EXISTS ck_pago_bonos;
ALTER TABLE PAGO_EMPLEADO
    ADD CONSTRAINT ck_pago_monto CHECK (monto_total >= 0),
    ADD CONSTRAINT ck_pago_dias CHECK (dias_trabajados BETWEEN 0 AND 31),
    ADD CONSTRAINT ck_pago_bonos CHECK (bonos >= 0);

ALTER TABLE EVENTO_SANITARIO DROP CONSTRAINT IF EXISTS ck_evento_costo;
ALTER TABLE EVENTO_SANITARIO
    ADD CONSTRAINT ck_evento_costo CHECK (costo >= 0);

ALTER TABLE USUARIO DROP FOREIGN KEY IF EXISTS fk_usuario_empleado;
ALTER TABLE USUARIO
    ADD CONSTRAINT fk_usuario_empleado
        FOREIGN KEY (id_empleado) REFERENCES EMPLEADO(id_empleado)
        ON DELETE CASCADE;

ALTER TABLE USUARIO_ROL DROP FOREIGN KEY IF EXISTS fk_usuariorol_usuario;
ALTER TABLE USUARIO_ROL DROP FOREIGN KEY IF EXISTS fk_usuariorol_rol;
ALTER TABLE USUARIO_ROL
    ADD CONSTRAINT fk_usuariorol_usuario
        FOREIGN KEY (id_usuario) REFERENCES USUARIO(id_usuario)
        ON DELETE CASCADE,
    ADD CONSTRAINT fk_usuariorol_rol
        FOREIGN KEY (id_rol) REFERENCES ROL(id_rol)
        ON DELETE CASCADE;

ALTER TABLE ASISTENCIA DROP FOREIGN KEY IF EXISTS fk_asistencia_empleado;
ALTER TABLE ASISTENCIA
    ADD CONSTRAINT fk_asistencia_empleado
        FOREIGN KEY (id_empleado) REFERENCES EMPLEADO(id_empleado)
        ON DELETE CASCADE;

ALTER TABLE PAGO_EMPLEADO DROP FOREIGN KEY IF EXISTS fk_pago_empleado;
ALTER TABLE PAGO_EMPLEADO
    ADD CONSTRAINT fk_pago_empleado
        FOREIGN KEY (id_empleado) REFERENCES EMPLEADO(id_empleado)
        ON DELETE SET NULL;

ALTER TABLE VACA DROP FOREIGN KEY IF EXISTS fk_vaca_madre;
ALTER TABLE VACA
    ADD CONSTRAINT fk_vaca_madre
        FOREIGN KEY (id_madre) REFERENCES VACA(id_vaca)
        ON DELETE SET NULL;

ALTER TABLE HISTORIAL_CORRAL DROP FOREIGN KEY IF EXISTS fk_historial_vaca;
ALTER TABLE HISTORIAL_CORRAL DROP FOREIGN KEY IF EXISTS fk_historial_corral;
ALTER TABLE HISTORIAL_CORRAL MODIFY id_corral INT NULL;
ALTER TABLE HISTORIAL_CORRAL
    ADD CONSTRAINT fk_historial_vaca
        FOREIGN KEY (id_vaca) REFERENCES VACA(id_vaca)
        ON DELETE CASCADE,
    ADD CONSTRAINT fk_historial_corral
        FOREIGN KEY (id_corral) REFERENCES CORRAL(id_corral)
        ON DELETE SET NULL;

ALTER TABLE PRODUCCION_LECHE DROP FOREIGN KEY IF EXISTS fk_produccion_vaca;
ALTER TABLE PRODUCCION_LECHE DROP FOREIGN KEY IF EXISTS fk_produccion_lote;
ALTER TABLE PRODUCCION_LECHE MODIFY id_lote INT NULL;
ALTER TABLE PRODUCCION_LECHE
    ADD CONSTRAINT fk_produccion_vaca
        FOREIGN KEY (id_vaca) REFERENCES VACA(id_vaca)
        ON DELETE CASCADE,
    ADD CONSTRAINT fk_produccion_lote
        FOREIGN KEY (id_lote) REFERENCES LOTE_PRODUCCION(id_lote)
        ON DELETE SET NULL;

ALTER TABLE VENTA_LECHE DROP FOREIGN KEY IF EXISTS fk_venta_lote;
ALTER TABLE VENTA_LECHE DROP FOREIGN KEY IF EXISTS fk_venta_cliente;
ALTER TABLE VENTA_LECHE
    ADD CONSTRAINT fk_venta_lote
        FOREIGN KEY (id_lote) REFERENCES LOTE_PRODUCCION(id_lote)
        ON DELETE SET NULL,
    ADD CONSTRAINT fk_venta_cliente
        FOREIGN KEY (id_cliente) REFERENCES CLIENTE(id_cliente)
        ON DELETE SET NULL;

ALTER TABLE COMPRA_INSUMO DROP FOREIGN KEY IF EXISTS fk_compra_insumo;
ALTER TABLE COMPRA_INSUMO DROP FOREIGN KEY IF EXISTS fk_compra_proveedor;
ALTER TABLE COMPRA_INSUMO
    ADD CONSTRAINT fk_compra_insumo
        FOREIGN KEY (id_insumo) REFERENCES INSUMO(id_insumo)
        ON DELETE SET NULL,
    ADD CONSTRAINT fk_compra_proveedor
        FOREIGN KEY (id_proveedor) REFERENCES PROVEEDOR(id_proveedor)
        ON DELETE SET NULL;

ALTER TABLE EVENTO_SANITARIO DROP FOREIGN KEY IF EXISTS fk_evento_vaca;
ALTER TABLE EVENTO_SANITARIO DROP FOREIGN KEY IF EXISTS fk_evento_veterinario;
ALTER TABLE EVENTO_SANITARIO DROP FOREIGN KEY IF EXISTS fk_evento_insumo;
ALTER TABLE EVENTO_SANITARIO
    ADD CONSTRAINT fk_evento_vaca
        FOREIGN KEY (id_vaca) REFERENCES VACA(id_vaca)
        ON DELETE CASCADE,
    ADD CONSTRAINT fk_evento_veterinario
        FOREIGN KEY (id_veterinario) REFERENCES EMPLEADO(id_empleado)
        ON DELETE SET NULL,
    ADD CONSTRAINT fk_evento_insumo
        FOREIGN KEY (id_insumo) REFERENCES INSUMO(id_insumo)
        ON DELETE SET NULL;
