 USE establo;
 
ALTER TABLE EMPLEADO
    MODIFY nombre         VARCHAR(100) NOT NULL,
    MODIFY apellido       VARCHAR(100) NOT NULL,
    MODIFY fecha_contrato DATE NOT NULL,
    MODIFY salario_base   DECIMAL(10,2) NOT NULL;
 
ALTER TABLE VACA
    MODIFY arete            VARCHAR(50) NOT NULL,
    MODIFY fecha_nacimiento DATE NOT NULL,
    MODIFY estado           VARCHAR(50) NOT NULL;
 
ALTER TABLE CORRAL
    MODIFY capacidad INT NOT NULL;
 
ALTER TABLE LOTE_PRODUCCION
    MODIFY nombre_lote  VARCHAR(100) NOT NULL,
    MODIFY fecha_inicio DATE NOT NULL;
 
ALTER TABLE PRODUCCION_LECHE
    MODIFY fecha  DATE NOT NULL,
    MODIFY litros DECIMAL(5,2) NOT NULL;
 
ALTER TABLE VENTA_LECHE
    MODIFY fecha           DATE NOT NULL,
    MODIFY litros_vendidos DECIMAL(8,2) NOT NULL,
    MODIFY precio_por_litro DECIMAL(6,2) NOT NULL;
