USE establo;

ALTER TABLE ASISTENCIA DROP FOREIGN KEY asistencia_ibfk_1;
ALTER TABLE ASISTENCIA ADD CONSTRAINT fk_asistencia_empleado 
    FOREIGN KEY (id_empleado) REFERENCES EMPLEADO(id_empleado) 
    ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE VACA DROP FOREIGN KEY vaca_ibfk_1;
ALTER TABLE VACA ADD CONSTRAINT fk_vaca_madre 
    FOREIGN KEY (id_madre) REFERENCES VACA(id_vaca) 
    ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE produccion_leche DROP FOREIGN KEY produccion_leche_ibfk_1;
ALTER TABLE produccion_leche ADD CONSTRAINT fk_produccion_vaca 
    FOREIGN KEY (id_vaca) REFERENCES VACA(id_vaca) 
    ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE COMPRA_INSUMO DROP FOREIGN KEY compra_insumo_ibfk_1;
ALTER TABLE COMPRA_INSUMO ADD CONSTRAINT fk_compra_proveedor 
    FOREIGN KEY (id_proveedor) REFERENCES PROVEEDOR(id_proveedor) 
    ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE VENTA_LECHE DROP FOREIGN KEY venta_leche_ibfk_1;
ALTER TABLE VENTA_LECHE ADD CONSTRAINT fk_venta_cliente 
    FOREIGN KEY (id_cliente) REFERENCES CLIENTE(id_cliente) 
    ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE HISTORIAL_CORRAL DROP FOREIGN KEY historial_corral_ibfk_1;
ALTER TABLE HISTORIAL_CORRAL DROP FOREIGN KEY historial_corral_ibfk_2;
ALTER TABLE HISTORIAL_CORRAL 
    ADD CONSTRAINT fk_historial_vaca FOREIGN KEY (id_vaca) REFERENCES VACA(id_vaca) ON DELETE CASCADE ON UPDATE CASCADE,
    ADD CONSTRAINT fk_historial_corral FOREIGN KEY (id_corral) REFERENCES CORRAL(id_corral) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE EVENTO_SANITARIO DROP FOREIGN KEY evento_sanitario_ibfk_1;
ALTER TABLE EVENTO_SANITARIO ADD CONSTRAINT fk_evento_vaca 
    FOREIGN KEY (id_vaca) REFERENCES VACA(id_vaca) 
    ON DELETE CASCADE ON UPDATE CASCADE;
