USE establo;
EXPLAIN SELECT * FROM PRODUCCION_LECHE WHERE id_vaca = 1;
EXPLAIN SELECT * FROM PRODUCCION_LECHE WHERE fcha BETWEEN '2024-01-01' AND '2024-12-31';
EXPLAIN SELECT * FROM EVENTO_SANITARIO WHERE id_vaca = 1;
EXPLAIN SELECT * FROM COMPRA_INSUMO WHERE id_proveedor = 1;
EXPLAIN SELECT * FROM HISTORIAL_CORRAL WHERE id_vaca = 1 AND fcha_slida IS NULL;
