USE establo;
 

EXPLAIN SELECT * FROM PRODUCCION_LECHE
WHERE id_vaca = 5 AND fecha BETWEEN '2026-01-01' AND '2026-06-30';
 
CREATE INDEX idx_produccion_vaca_fecha ON PRODUCCION_LECHE (id_vaca, fecha);
 
-- ANTES:
EXPLAIN SELECT * FROM VENTA_LECHE
WHERE fecha BETWEEN '2026-06-01' AND '2026-06-30';
 
CREATE INDEX idx_venta_fecha ON VENTA_LECHE (fecha);
