USE establo;

ALTER TABLE EMPLEADO
MODIFY nombre VARCHAR(100) NOT NULL,
MODIFY apellido VARCHAR(100) NOT NULL,
MODIFY cargo VARCHAR(100) NOT NULL,
MODIFY fecha_contrato DATE NOT NULL,
MODIFY salario_base DECIMAL(10,2) NOT NULL;

ALTER TABLE VACA
MODIFY arete VARCHAR(50) NOT NULL,
MODIFY fecha_ingreso DATE NOT NULL;

ALTER TABLE CORRAL
MODIFY nombre VARCHAR(50) NOT NULL,
MODIFY capacidad INT NOT NULL;

ALTER TABLE INSUMO
MODIFY nombre VARCHAR(100) NOT NULL;

ALTER TABLE PAGO_EMPLEADO
MODIFY mes VARCHAR(20) NOT NULL,
MODIFY monto_total DECIMAL(10,2) NOT NULL,
MODIFY fecha_pago DATE NOT NULL;
