USE establo;

ALTER TABLE EMPLEADO
MODIFY nombre VARCHAR(100),
MODIFY apellido VARCHAR(100),
MODIFY cargo VARCHAR(100);

ALTER TABLE VACA
MODIFY arete VARCHAR(50),
MODIFY fecha_ingreso DATE;

ALTER TABLE CORRAL
MODIFY nombre VARCHAR(50);
